//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.06 at 10:48:47 AM CEST 
//


package com.localhost.spring_practices;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for infoPersonResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="infoPersonResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="person" type="{http://localhost.com/spring_practices}personType"/&gt;
 *         &lt;element name="listCar" type="{http://localhost.com/spring_practices}listCarType"/&gt;
 *         &lt;element name="listHotel" type="{http://localhost.com/spring_practices}listHotelType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "infoPersonResponse", propOrder = {
    "person",
    "listCar",
    "listHotel"
})
public class InfoPersonResponse {

    @XmlElement(required = true)
    protected PersonType person;
    @XmlElement(required = true)
    protected ListCarType listCar;
    @XmlElement(required = true)
    protected ListHotelType listHotel;

    /**
     * Gets the value of the person property.
     * 
     * @return
     *     possible object is
     *     {@link PersonType }
     *     
     */
    public PersonType getPerson() {
        return person;
    }

    /**
     * Sets the value of the person property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonType }
     *     
     */
    public void setPerson(PersonType value) {
        this.person = value;
    }

    /**
     * Gets the value of the listCar property.
     * 
     * @return
     *     possible object is
     *     {@link ListCarType }
     *     
     */
    public ListCarType getListCar() {
        return listCar;
    }

    /**
     * Sets the value of the listCar property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListCarType }
     *     
     */
    public void setListCar(ListCarType value) {
        this.listCar = value;
    }

    /**
     * Gets the value of the listHotel property.
     * 
     * @return
     *     possible object is
     *     {@link ListHotelType }
     *     
     */
    public ListHotelType getListHotel() {
        return listHotel;
    }

    /**
     * Sets the value of the listHotel property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListHotelType }
     *     
     */
    public void setListHotel(ListHotelType value) {
        this.listHotel = value;
    }

}
