//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.06 at 10:48:47 AM CEST 
//


package com.localhost.spring_practices;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.localhost.spring_practices package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _InfoPersonRequest_QNAME = new QName("http://localhost.com/spring_practices", "infoPersonRequest");
    private final static QName _InfoPersonResponse_QNAME = new QName("http://localhost.com/spring_practices", "infoPersonResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.localhost.spring_practices
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link InfoPersonRequest }
     * 
     */
    public InfoPersonRequest createInfoPersonRequest() {
        return new InfoPersonRequest();
    }

    /**
     * Create an instance of {@link InfoPersonResponse }
     * 
     */
    public InfoPersonResponse createInfoPersonResponse() {
        return new InfoPersonResponse();
    }

    /**
     * Create an instance of {@link PersonType }
     * 
     */
    public PersonType createPersonType() {
        return new PersonType();
    }

    /**
     * Create an instance of {@link ListHotelType }
     * 
     */
    public ListHotelType createListHotelType() {
        return new ListHotelType();
    }

    /**
     * Create an instance of {@link ListCarType }
     * 
     */
    public ListCarType createListCarType() {
        return new ListCarType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InfoPersonRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://localhost.com/spring_practices", name = "infoPersonRequest")
    public JAXBElement<InfoPersonRequest> createInfoPersonRequest(InfoPersonRequest value) {
        return new JAXBElement<InfoPersonRequest>(_InfoPersonRequest_QNAME, InfoPersonRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InfoPersonResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://localhost.com/spring_practices", name = "infoPersonResponse")
    public JAXBElement<InfoPersonResponse> createInfoPersonResponse(InfoPersonResponse value) {
        return new JAXBElement<InfoPersonResponse>(_InfoPersonResponse_QNAME, InfoPersonResponse.class, null, value);
    }

}
